ProductInventory/src/objects/Product_Info__c.object
<CustomObject>
    <fields>
        <fullName>product_quantity__c</fullName>
        <label>product_quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>purchase_price__c</fullName>
        <label>purchase_price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sale_price__c</fullName>
        <label>sale_price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product_Info</label>
    <nameField>
        <label>Product_Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product_Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProductInventory/src/classes/GenerateDataTest.cls
@isTest
public class GenerateDataTest {
	@isTest
    public static void productTestData(){
        List<Product_info__c> productList= new List<Product_info__c>();
        for(Integer i=0;i<10;i++){
            Product_info__c product=new Product_info__c();
            product.Name='Product'+i;
            product.purchase_price__c=i;
            product.sale_price__c=i+2;
            product.product_quantity__c=50+i;
            productList.add(product);
        }
        insert productList;
    }
}